// Generated by CoffeeScript 1.12.7
(function() {
  var Client, _, apiClient;

  _ = require('underscore');

  apiClient = require('./api_client');

  Client = (function() {
    function Client(options) {
      this.api = new apiClient.APIClient(options);
    }

    Client.prototype.cachesList = function(options, cb) {
      return this.api.cachesList(options, function(error, body) {
        if (error == null) {
          return cb(error, body.codes);
        } else {
          return cb(error, body);
        }
      });
    };

    return Client;

  })();

  module.exports.Client = Client;

}).call(this);
